# Generated by Django 5.2.8 on 2026-01-07 05:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sclad", "0004_remove_recipe_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Партия ГП"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="Продукт"),
                ),
                (
                    "quantity_produced",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0.001)],
                        verbose_name="Количество",
                    ),
                ),
                ("produced_at", models.DateTimeField(verbose_name="Дата производства")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-produced_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductionComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_used",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0.001)],
                        verbose_name="Списано",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sclad.rawmaterial",
                    ),
                ),
                (
                    "production",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="production.productionbatch",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sclad.rawmaterialreceipt",
                        verbose_name="Партия склада",
                    ),
                ),
            ],
        ),
    ]
