# Generated by Django 5.2.8 on 2025-12-02 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=255, verbose_name='Клиент')),
                ('product_name', models.CharField(max_length=255, verbose_name='Продукт')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('current_stage', models.CharField(choices=[('mixing', 'Смешивание'), ('extrusion', 'Экструзия'), ('forming', 'Формовка'), ('cooling', 'Охлаждение'), ('packing', 'Упаковка')], default='mixing', max_length=32, verbose_name='Текущий этап')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=16, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('done', 'Завершён'), ('canceled', 'Отменён')], default='new', max_length=16, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_orders', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
            ],
            options={
                'verbose_name': 'Заказ на производство',
                'verbose_name_plural': 'Заказы на производство',
                'ordering': ['-created_at'],
            },
        ),
    ]
