# Generated by Django 5.2.8 on 2026-01-07 14:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
        ("sclad", "0005_stocktransaction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productionbatch",
            options={
                "ordering": ["-produced_at"],
                "verbose_name": "Партия производства",
                "verbose_name_plural": "Партии производства",
            },
        ),
        migrations.AlterModelOptions(
            name="productioncomponent",
            options={
                "verbose_name": "Компонент производства",
                "verbose_name_plural": "Компоненты производства",
            },
        ),
        migrations.AddField(
            model_name="productioncomponent",
            name="unit",
            field=models.CharField(
                default=1, max_length=20, verbose_name="Единица измерения"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productionbatch",
            name="quantity_produced",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0.001)],
                verbose_name="Количество произведено",
            ),
        ),
        migrations.AlterField(
            model_name="productioncomponent",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="sclad.rawmaterial",
                verbose_name="Сырьё",
            ),
        ),
        migrations.AlterField(
            model_name="productioncomponent",
            name="production",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="production.productionbatch",
                verbose_name="Партия производства",
            ),
        ),
    ]
