# Generated by Django 5.2.8 on 2025-12-13 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        ('production_control', '0002_alter_productionline_identifier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='quantity',
        ),
        migrations.AddField(
            model_name='productionorder',
            name='color',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='defect_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Брак (кг)'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='produced_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Произведено (кг)'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='production_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='production_control.productionline', verbose_name='Производственная линия'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='quantity_planned',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='План (кг)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionorder',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('done', 'Завершён'), ('rejected', 'В браке'), ('canceled', 'Отменён')], default='new', max_length=16, verbose_name='Статус'),
        ),
    ]
