# Generated by Django 5.2.8 on 2025-12-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_remove_productionorder_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='quantity_planned',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='План (кг)'),
        ),
    ]
