# Generated by Django 5.2.8 on 2026-01-07 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0002_alter_productionbatch_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionbatch",
            name="quantity_produced",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0.1)],
                verbose_name="Количество произведено",
            ),
        ),
        migrations.AlterField(
            model_name="productioncomponent",
            name="quantity_used",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0.1)],
                verbose_name="Списано",
            ),
        ),
        migrations.AlterField(
            model_name="productioncomponent",
            name="unit",
            field=models.CharField(
                default="kg", max_length=20, verbose_name="Единица измерения"
            ),
        ),
    ]
