# Generated by Django 5.2.8 on 2025-12-17 06:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_productionorder_quantity_planned'),
        ('production_control', '0002_alter_productionline_identifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionDowntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('no_material', 'Нет сырья'), ('breakdown', 'Поломка'), ('setup', 'Переналадка'), ('quality', 'Проблема качества'), ('other', 'Другое')], default='other', max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtimes', to='production.productionorder')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtimes', to='production_control.productionline')),
            ],
            options={
                'verbose_name': 'Простой',
                'verbose_name_plural': 'Простои',
                'ordering': ['-started_at'],
            },
        ),
    ]
