# Generated by Django 5.2.8 on 2026-01-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0003_alter_productionbatch_quantity_produced_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionbatch",
            name="quality_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает ОТК"),
                    ("passed", "Пройдено"),
                    ("failed", "Брак"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус ОТК",
            ),
        ),
    ]
