# Generated by Django 5.2.8 on 2025-12-17 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_productiondowntime'),
        ('recipes', '0002_alter_recipe_options_alter_recipeitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='recipe_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='recipes.recipeversion', verbose_name='Рецептура (версия)'),
        ),
    ]
