# Generated by Django 5.2.8 on 2026-01-07 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
        ("production", "0004_productionbatch_quality_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionbatch",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="production_batches",
                to="order.productionorder",
                verbose_name="Производственный заказ",
            ),
        ),
    ]
