# Generated by Django 5.2.8 on 2026-01-09 06:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0006_productionbatch_operator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productionbatch",
            name="defect_reason",
            field=models.TextField(blank=True, null=True, verbose_name="Причина брака"),
        ),
        migrations.AddField(
            model_name="productionbatch",
            name="quality_checked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата проверки ОТК"
            ),
        ),
        migrations.AddField(
            model_name="productionbatch",
            name="quality_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Комментарий ОТК"
            ),
        ),
        migrations.AddField(
            model_name="productionbatch",
            name="quality_inspector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quality_checked_batches",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Инспектор ОТК",
            ),
        ),
        migrations.AddField(
            model_name="productionbatch",
            name="quantity_accepted",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Принято (шт)",
            ),
        ),
        migrations.AddField(
            model_name="productionbatch",
            name="quantity_defective",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Брак (шт)",
            ),
        ),
    ]
