# Generated by Django 5.2.8 on 2026-01-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0007_productionbatch_defect_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionbatch",
            name="quality_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает ОТК"),
                    ("passed", "Принято"),
                    ("passed_with_defects", "Принято с браком"),
                    ("failed", "Полный брак"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус ОТК",
            ),
        ),
    ]
