# Generated by Django 5.2.8 on 2026-01-09 15:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0008_alter_productionbatch_quality_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinishedProductMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("production", "Производство"),
                            ("quality_accepted", "Принято ОТК"),
                            ("quality_rejected", "Брак ОТК"),
                            ("shipment", "Отгрузка"),
                            ("return", "Возврат"),
                        ],
                        max_length=20,
                        verbose_name="Тип операции",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="Продукт"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата операции"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_movements",
                        to="production.productionbatch",
                        verbose_name="Партия производства",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Движение готовой продукции",
                "verbose_name_plural": "Движения готовой продукции",
            },
        ),
    ]
