# Generated by Django 5.2.8 on 2026-01-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0009_finishedproductmovement"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FinishedProductMovement",
        ),
    ]
