# Generated by Django 5.2.8 on 2025-12-02 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=255, verbose_name='Клиент')),
                ('order_number', models.CharField(max_length=64, unique=True, verbose_name='Номер заказа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма заказа')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_work', 'В работе'), ('confirmed', 'Подтверждена'), ('declined', 'Отказ')], default='new', max_length=16, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_orders', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
            ],
            options={
                'verbose_name': 'Заказ клиента',
                'verbose_name_plural': 'Заказы клиентов',
                'ordering': ['-created_at'],
            },
        ),
    ]
