# Generated by Django 5.2.8 on 2025-12-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='system_role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('user', 'Пользователь')], max_length=20),
        ),
    ]
