# Generated by Django 5.2.8 on 2025-12-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_system_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="ФИО"
            ),
        ),
    ]
