# Generated by Django 5.2.8 on 2025-12-01 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='Артикул (SKU)')),
                ('stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Остаток на складе')),
                ('reserved', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Резерв (под подтверждённые заказы)')),
            ],
            options={
                'verbose_name': 'Готовая продукция',
                'verbose_name_plural': 'Готовая продукция',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('material_type', models.CharField(choices=[('granules', 'Гранулы'), ('color', 'Краситель'), ('additive', 'Добавка'), ('package', 'Упаковка'), ('other', 'Другое')], max_length=20, verbose_name='Тип сырья')),
                ('unit', models.CharField(choices=[('kg', 'кг'), ('t', 'т'), ('l', 'л'), ('pcs', 'шт')], default='kg', max_length=10, verbose_name='Ед. измерения')),
                ('min_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Минимальный остаток')),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Текущий остаток')),
            ],
            options={
                'verbose_name': 'Сырьё',
                'verbose_name_plural': 'Сырьё',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_type', models.CharField(choices=[('in', 'Поступление'), ('out', 'Расход')], max_length=3, verbose_name='Тип операции')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('document', models.CharField(blank=True, max_length=255, verbose_name='Документ (накладная, заказ и т.п.)')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='sclad.rawmaterial')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_material_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Движение сырья',
                'verbose_name_plural': 'Движения сырья',
                'ordering': ['-created_at'],
            },
        ),
    ]
