# Generated by Django 5.2.8 on 2025-12-24 12:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sclad", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawMaterialReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата прихода")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0.001)],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Номер партии",
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Поставщик"
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
            ],
            options={
                "verbose_name": "Приход сырья",
                "verbose_name_plural": "Приход сырья",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.DeleteModel(
            name="FinishedProduct",
        ),
        migrations.AlterModelOptions(
            name="rawmaterial",
            options={
                "ordering": ["id"],
                "verbose_name": "Сырьё",
                "verbose_name_plural": "Справочник сырья",
            },
        ),
        migrations.AlterModelOptions(
            name="rawmaterialmovement",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Движение сырья",
                "verbose_name_plural": "Движения сырья",
            },
        ),
        migrations.RemoveField(
            model_name="rawmaterial",
            name="current_stock",
        ),
        migrations.RemoveField(
            model_name="rawmaterial",
            name="material_type",
        ),
        migrations.RemoveField(
            model_name="rawmaterial",
            name="min_stock",
        ),
        migrations.RemoveField(
            model_name="rawmaterialmovement",
            name="document",
        ),
        migrations.RemoveField(
            model_name="rawmaterialmovement",
            name="performed_by",
        ),
        migrations.RemoveField(
            model_name="rawmaterialmovement",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="rawmaterial",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="rawmaterial",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="rawmaterial",
            name="unit",
            field=models.CharField(
                choices=[("g", "г"), ("kg", "кг"), ("ml", "мл"), ("l", "л")],
                default="kg",
                max_length=5,
                verbose_name="Единица измерения",
            ),
        ),
        migrations.AlterField(
            model_name="rawmaterial",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="rawmaterialmovement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="rawmaterialmovement",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="sclad.rawmaterial",
                verbose_name="Сырьё",
            ),
        ),
        migrations.AlterField(
            model_name="rawmaterialmovement",
            name="operation_type",
            field=models.CharField(
                choices=[("in", "Приход"), ("out", "Расход")],
                max_length=10,
                verbose_name="Тип операции",
            ),
        ),
        migrations.AlterField(
            model_name="rawmaterialmovement",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, verbose_name="Количество"
            ),
        ),
        migrations.AddField(
            model_name="rawmaterialreceipt",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipts",
                to="sclad.rawmaterial",
                verbose_name="Сырьё",
            ),
        ),
        migrations.AddField(
            model_name="rawmaterialmovement",
            name="receipt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movements",
                to="sclad.rawmaterialreceipt",
                verbose_name="Документ прихода",
            ),
        ),
    ]
