# Generated by Django 5.2.8 on 2025-12-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sclad", "0003_recipe_alter_rawmaterial_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="code",
        ),
    ]
