# Generated by Django 5.2.8 on 2026-01-07 14:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sclad", "0004_remove_recipe_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        max_length=120, verbose_name="Номер партии склада"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Положительное для прихода, отрицательное для списания",
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0.001)],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("receipt", "Приход"), ("production", "Производство")],
                        max_length=20,
                        verbose_name="Тип операции",
                    ),
                ),
                ("reference_id", models.UUIDField(verbose_name="ID связанной записи")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата операции"
                    ),
                ),
                (
                    "raw_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="sclad.rawmaterial",
                        verbose_name="Сырьё",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция склада",
                "verbose_name_plural": "Транзакции склада",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["batch_number", "raw_material"],
                        name="sclad_stock_batch_n_6621d8_idx",
                    ),
                    models.Index(
                        fields=["transaction_type", "created_at"],
                        name="sclad_stock_transac_360049_idx",
                    ),
                ],
            },
        ),
    ]
