# Generated by Django 5.2.8 on 2026-01-07 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sclad", "0005_stocktransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawmaterialmovement",
            name="quantity",
            field=models.DecimalField(
                decimal_places=1, max_digits=14, verbose_name="Количество"
            ),
        ),
        migrations.AlterField(
            model_name="rawmaterialreceipt",
            name="quantity",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0.1)],
                verbose_name="Количество",
            ),
        ),
        migrations.AlterField(
            model_name="recipeitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0.1)],
                verbose_name="Количество",
            ),
        ),
        migrations.DeleteModel(
            name="StockTransaction",
        ),
    ]
