# Generated by Django 5.2.8 on 2026-01-09 16:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0010_delete_finishedproductmovement"),
        ("sclad", "0006_alter_rawmaterialmovement_quantity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinishedProductBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Номер партии ГП"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="Продукт"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                        verbose_name="Количество",
                    ),
                ),
                ("production_date", models.DateField(verbose_name="Дата производства")),
                (
                    "acceptance_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата приёмки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Доступно"),
                            ("reserved", "Зарезервировано"),
                            ("shipped", "Отгружено"),
                            ("expired", "Просрочено"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_finished_batches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Принял на склад",
                    ),
                ),
                (
                    "production_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finished_batches",
                        to="production.productionbatch",
                        verbose_name="Партия производства",
                    ),
                ),
            ],
            options={
                "verbose_name": "Партия готовой продукции",
                "verbose_name_plural": "Партии готовой продукции",
                "ordering": ["-acceptance_date"],
            },
        ),
        migrations.CreateModel(
            name="FinishedProductMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("production", "Производство"),
                            ("quality_accepted", "Принято ОТК"),
                            ("quality_rejected", "Брак ОТК"),
                            ("warehouse_acceptance", "Приёмка на склад ГП"),
                            ("shipment", "Отгрузка"),
                            ("return", "Возврат"),
                            ("write_off", "Списание"),
                        ],
                        max_length=30,
                        verbose_name="Тип операции",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="Продукт"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата операции"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_movements",
                        to="production.productionbatch",
                        verbose_name="Партия производства",
                    ),
                ),
                (
                    "finished_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="sclad.finishedproductbatch",
                        verbose_name="Партия ГП",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Движение готовой продукции",
                "verbose_name_plural": "Движения готовой продукции",
            },
        ),
    ]
