# Generated by Django 5.2.8 on 2025-12-06 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Код/номер линии, например L1, EXT-01', max_length=50, unique=True, verbose_name='Идентификатор линии')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('status', models.CharField(choices=[('running', 'Работает'), ('stopped', 'Остановлена'), ('maintenance', 'Обслуживание')], default='running', max_length=20, verbose_name='Статус')),
                ('speed_percent', models.PositiveIntegerField(default=0, help_text='0–100, можно использовать как относительную скорость', verbose_name='Скорость, %')),
                ('output_per_shift', models.PositiveIntegerField(default=0, help_text='Количество произведённой продукции за смену', verbose_name='Выпуск за смену')),
                ('last_maintenance_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее обслуживание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('monitored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_lines', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный оператор')),
            ],
            options={
                'verbose_name': 'Производственная линия',
                'verbose_name_plural': 'Производственные линии',
                'ordering': ['identifier'],
            },
        ),
    ]
