# Generated by Django 5.2.8 on 2025-12-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionline',
            name='identifier',
            field=models.CharField(help_text='Код/номер линии, например L1, L2, EXT-01', max_length=50, unique=True, verbose_name='Идентификатор линии'),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='output_per_shift',
            field=models.PositiveIntegerField(default=0, verbose_name='Выпуск за смену (условно)'),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='speed_percent',
            field=models.PositiveIntegerField(default=0, help_text='0–100', verbose_name='Скорость, %'),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='status',
            field=models.CharField(choices=[('running', 'Работает'), ('stopped', 'Остановлена'), ('maintenance', 'Обслуживание'), ('idle', 'Простой')], default='idle', max_length=20, verbose_name='Статус'),
        ),
    ]
