# Generated by Django 5.2.8 on 2025-12-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production_control", "0002_alter_productionline_identifier_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productionline",
            options={
                "ordering": ["name"],
                "verbose_name": "Производственная линия",
                "verbose_name_plural": "Производственные линии",
            },
        ),
        migrations.RemoveField(
            model_name="productionline",
            name="identifier",
        ),
        migrations.RemoveField(
            model_name="productionline",
            name="last_maintenance_at",
        ),
        migrations.RemoveField(
            model_name="productionline",
            name="monitored_by",
        ),
        migrations.RemoveField(
            model_name="productionline",
            name="output_per_shift",
        ),
        migrations.RemoveField(
            model_name="productionline",
            name="speed_percent",
        ),
        migrations.RemoveField(
            model_name="productionline",
            name="status",
        ),
        migrations.AlterField(
            model_name="productionline",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название линии"
            ),
        ),
    ]
