# Generated by Django 5.2.8 on 2025-12-16 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('unit', models.CharField(choices=[('kg', 'кг'), ('g', 'г')], default='kg', max_length=8)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('supplier', models.CharField(blank=True, default='', max_length=255)),
                ('min_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Сырьё/материал',
                'verbose_name_plural': 'Сырьё/материалы',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='warehouse_m_name_7d4e7c_idx'), models.Index(fields=['code'], name='warehouse_m_code_cf4dc8_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaterialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('in', 'Приход'), ('out', 'Расход'), ('transfer', 'Перемещение'), ('adjustment', 'Корректировка')], max_length=16)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_movements', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='warehouse.material')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_out', to='warehouse.warehouse')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_in', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Движение сырья',
                'verbose_name_plural': 'Движения сырья',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Остаток')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='warehouse.material')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Остаток сырья',
                'verbose_name_plural': 'Остатки сырья',
                'ordering': ['warehouse__name', 'material__name'],
                'unique_together': {('material', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='MaterialReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_order_id', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_reservations', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='warehouse.material')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Резерв сырья',
                'verbose_name_plural': 'Резервы сырья',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['production_order_id'], name='warehouse_m_product_9a49fd_idx')],
            },
        ),
    ]
