# Generated by Django 5.2.8 on 2025-12-06 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Клиент')),
                ('city', models.CharField(max_length=255, verbose_name='Город / пункт доставки')),
                ('pallets_count', models.PositiveIntegerField(verbose_name='Кол-во паллет')),
                ('status', models.CharField(choices=[('planning', 'Планирование'), ('loading', 'Погрузка'), ('in_transit', 'В пути'), ('delivered', 'Доставлено')], default='planning', max_length=20, verbose_name='Статус')),
                ('eta_hours', models.PositiveIntegerField(blank=True, help_text='Можно оставлять пустым, если ещё не посчитан', null=True, verbose_name='Прогноз ETA (часы до доставки)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
            ],
            options={
                'verbose_name': 'Отгрузка',
                'verbose_name_plural': 'Отгрузки',
                'ordering': ['-created_at'],
            },
        ),
    ]
