# Generated by Django 5.2.8 on 2025-12-06 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Продукт')),
                ('defect_type', models.CharField(max_length=255, verbose_name='Тип дефекта')),
                ('lot', models.CharField(max_length=100, verbose_name='Партия (lot)')),
                ('severity', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], default='medium', max_length=10, verbose_name='Важность')),
                ('corrective_actions', models.TextField(blank=True, verbose_name='Корректирующие действия')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время выявления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_issues', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Несоответствие',
                'verbose_name_plural': 'Журнал несоответствий',
                'ordering': ['-created_at'],
            },
        ),
    ]
