# Generated by Django 5.2.8 on 2025-12-17 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=255, verbose_name='Продукт')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активная')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Рецептура',
                'verbose_name_plural': 'Рецептуры',
                'ordering': ['product_name', '-version'],
                'unique_together': {('product_name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_name', models.CharField(max_length=255, verbose_name='Сырьё')),
                ('norm_per_kg', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Норма на 1 кг продукции')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Позиция рецептуры',
                'verbose_name_plural': 'Позиции рецептуры',
                'ordering': ['id'],
            },
        ),
    ]
