# Generated by Django 5.2.8 on 2025-12-17 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        ('sclad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at'], 'verbose_name': 'Рецептура', 'verbose_name_plural': 'Рецептуры'},
        ),
        migrations.AlterModelOptions(
            name='recipeitem',
            options={'verbose_name': 'Компонент рецептуры', 'verbose_name_plural': 'Компоненты рецептуры'},
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='material_name',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='norm_per_kg',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_items', to='sclad.rawmaterial', verbose_name='Сырьё'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='qty_per_kg',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=12, verbose_name='Норма (кг на 1 кг)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Продукт'),
        ),
        migrations.CreateModel(
            name='RecipeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recipe_versions', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Версия рецептуры',
                'verbose_name_plural': 'Версии рецептур',
                'ordering': ['-version', '-created_at'],
                'unique_together': {('recipe', 'version')},
            },
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recipes.recipeversion'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='note',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='version',
        ),
    ]
